INSERT INTO `race` (`nom`,`id_espece`)VALUES
	('affenpinscher',1),
    ('airedale terrier',1),
    ('akita',1),
    ('akita americain',1),
    ('anglo francais de petite venerie',1),
    ('ariegeois',1),
    ('azawakh',1),
    ('bangkaew de thailande',1),
    ('barbet',1),
    ('barbu tcheque',1),
    ('barzoï',1),
    ('basenji',1),
    ('basset artesien normand',1),
    ('basset bleu de gascogne',1),
    ('basset de westphalie',1),
    ('basset des alpes',1),
    ('basset fauve de bretagne',1),
    ('basset hound',1),
    ('basset suedois',1),
    ('beagle',1),
    ('beagle harrier',1),
    ('bearded collie',1),
    ('bedlington terrier',1),
    ('berger allemand',1),
    ('berger australien',1),
    ('berger belge',1),
    ('berger bergamasque',1),
    ('berger blanc suisse',1),
    ('berger d''asie centrale',1),
    ('berger de beauce',1),
    ('berger de bosnie-herzegovine et de croatie',1),
    ('berger de brie',1),
    ('berger de la maremme et des abruzzes',1),
    ('berger de la serra de aires',1),
    ('berger de picardie',1),
    ('berger de russie meridionale',1),
    ('berger des pyrenees a face rase',1),
    ('berger des pyrenees a poil long',1),
    ('berger du caucase',1),
    ('berger du karst',1),
    ('berger finnois de laponie',1),
    ('berger hollandais',1),
    ('berger polonais de plaine',1),
    ('bichon a poil frise',1),
    ('bichon bolonais',1),
    ('bichon havanais',1),
    ('bichon maltais',1),
    ('billy',1),
    ('border collie',1),
    ('border terrier',1),
    ('bouledogue francais',1),
    ('bouvier australien',1),
    ('bouvier australien courte queue',1),
    ('bouvier bernois',1),
    ('bouvier de l''appenzell',1),
    ('bouvier de l''entlebuch',1),
    ('bouvier des ardennes',1),
    ('bouvier des flandres',1),
    ('boxer',1),
    ('brachet allemand',1),
    ('brachet de styrie a poil dur',1),
    ('brachet noir et feu',1),
    ('brachet polonais',1),
    ('brachet tyrolien',1),
    ('braque allemand a poil court',1),
    ('braque d auvergne',1),
    ('braque de burgos',1),
    ('braque de l ariege',1),
    ('braque de weimar',1),
    ('braque du bourbonnais',1),
    ('braque francais, type gascogne',1),
    ('braque francais, type pyrenees',1),
    ('braque hongrois a poil court',1),
    ('braque hongrois a poil dur',1),
    ('braque italien',1),
    ('braque saint germain',1),
    ('braque slovaque a poil dur',1),
    ('briquet de provence',1),
    ('briquet griffon vendeen',1),
    ('broholmer',1),
    ('bruno saint-hubert francais',1),
    ('buhund norvegien',1),
    ('bull terrier',1),
    ('bull terrier miniature',1),
    ('bulldog',1),
    ('bullmastiff',1),
    ('cairn terrier',1),
    ('caniche',1),
    ('carlin',1),
    ('cavalier king charles',1),
    ('chien a loutre',1),
    ('chien chinois a crete',1),
    ('chien courant d''istrie a poil dur',1),
    ('chien courant d''istrie a poil ras',1),
    ('chien courant de bosnie a poil dur',1),
    ('chien courant de halden',1),
    ('chien courant de hamilton',1),
    ('chien courant de hygen',1),
    ('chien courant de la valle de la save',1),
    ('chien courant de montagne du montenegro',1),
    ('chien courant de schiller',1),
    ('chien courant de transylvanie',1),
    ('chien courant du smaland',1),
    ('chien courant espagnol',1),
    ('chien courant finlandais',1),
    ('chien courant grec',1),
    ('chien courant italien a poil dur',1),
    ('chien courant italien a poil ras',1),
    ('chien courant norvegien',1),
    ('chien courant polonais',1),
    ('chien courant serbe',1),
    ('chien courant slovaque',1),
    ('chien courant suisse',1),
    ('chien courant tricolore serbe',1),
    ('chien d''arret allemand a poil dur',1),
    ('chien d''arret allemand a poil long',1),
    ('chien d''arret allemand a poil raide',1),
    ('chien d''arret danois ancestral',1),
    ('chien d''arret frison',1),
    ('chien d''arret portugais',1),
    ('chien d''artois',1),
    ('chien d''eau americain',1),
    ('chien d''eau espagnol',1),
    ('chien d''eau frison',1),
    ('chien d''eau portugais',1),
    ('chien d''eau romagnol',1),
    ('chien d''elan norvegien gris',1),
    ('chien d''elan norvegien noir',1),
    ('chien d''elan suedois / jämthund',1),
    ('chien d''ours de carelie',1),
    ('chien d''oysel allemand',1),
    ('chien de berger anglais ancestral',1),
    ('chien de berger catalan',1),
    ('chien de berger croate',1),
    ('chien de berger d anatolie',1),
    ('chien de berger de majorque',1),
    ('chien de berger des shetland',1),
    ('chien de berger des tatras',1),
    ('chien de berger islandais',1),
    ('chien de berger roumain de mioritza',1),
    ('chien de berger roumain des carpathes',1),
    ('chien de berger yougoslave de charplanina',1),
    ('chien de canaan',1),
    ('chien de castro laboreiro',1),
    ('chien de cour italien',1),
    ('chien de ferme dano-suedois',1),
    ('chien de garenne des canaries',1),
    ('chien de garenne portugais',1),
    ('chien de la serra da estrela',1),
    ('chien de leonberg',1),
    ('chien de montagne de l''atlas',1),
    ('chien de montagne des pyrenees',1),
    ('chien de perdrix de drente',1),
    ('chien de rhodesie a crete dorsale',1),
    ('chien de rouge de baviere',1),
    ('chien de rouge du hanovre',1),
    ('chien de saint hubert',1),
    ('chien de taïwan',1),
    ('chien du groenland',1),
    ('chien du pharaon',1),
    ('chien finnois de laponie',1),
    ('chien loup de saarloos',1),
    ('chien loup tchecoslovaque',1),
    ('chien norvegien de macareux',1),
    ('chien nu du perou',1),
    ('chien nu du mexique',1),
    ('chien thailandais a crete dorsale',1),
    ('chihuahua',1),
    ('chow chow',1),
    ('cimarron uruguayen',1),
    ('cirneco de l etna',1),
    ('clumber spaniel',1),
    ('cocker spaniel americain',1),
    ('cocker spaniel anglais',1),
    ('collie a poil court',1),
    ('collie a poil long',1),
    ('coton de tulear',1),
    ('cursinu',1),
    ('dalmatien',1),
    ('dandie dinmont terrier',1),
    ('dobermann',1),
    ('dogue allemand',1),
    ('dogue argentin',1),
    ('dogue de bordeaux',1),
    ('dogue de majorque',1),
    ('dogue des canaries',1),
    ('dogue du tibet',1),
    ('english springer spaniel',1),
    ('epagneul bleu de picardie',1),
    ('epagneul breton',1),
    ('epagneul d''eau irlandais',1),
    ('epagneul de pont audemer',1),
    ('epagneul de saint usuge',1),
    ('epagneul francais',1),
    ('epagneul japonais',1),
    ('epagneul king charles',1),
    ('epagneul nain continental',1),
    ('epagneul pekinois',1),
    ('epagneul picard',1),
    ('epagneul tibetain',1),
    ('esquimau du canada',1),
    ('eurasier',1),
    ('field spaniel',1),
    ('fila brasileiro',1),
    ('fila de saint miguel',1),
    ('fox hound anglais',1),
    ('fox terrier poil dur',1),
    ('fox terrier poil lisse',1),
    ('foxhound americain',1),
    ('francais blanc et noir',1),
    ('francais blanc et orange',1),
    ('francais tricolore',1),
    ('gascon saintongeois',1),
    ('golden retriever',1),
    ('grand anglo francais blanc et noir',1),
    ('grand anglo-francais blanc et orange',1),
    ('grand anglo-francais tricolore',1),
    ('grand basset griffon vendeen',1),
    ('grand bleu de gascogne',1),
    ('grand bouvier suisse',1),
    ('grand epagneul de munster',1),
    ('grand griffon vendeen',1),
    ('greyhound',1),
    ('griffon a poil dur korthals',1),
    ('griffon belge',1),
    ('griffon bleu de gascogne',1),
    ('griffon bruxellois',1),
    ('griffon fauve de bretagne',1),
    ('griffon nivernais',1),
    ('harrier',1),
    ('hokkaido',1),
    ('hovawart',1),
    ('husky de siberie',1),
    ('jindo coreen',1),
    ('kai',1),
    ('kelpie australien',1),
    ('kishu',1),
    ('komondor',1),
    ('kromfohrlander',1),
    ('kuvasz',1),
    ('laika de siberie occidentale',1),
    ('laika de siberie orientale',1),
    ('laika russo europeen',1),
    ('lakeland terrier',1),
    ('landseer',1),
    ('lapphund suedois',1),
    ('levrier afghan',1),
    ('levrier ecossais',1),
    ('levrier espagnol',1),
    ('levrier hongrois',1);
	
	
	
	
	
INSERT INTO `race` (`nom`,`id_espece`)VALUES
    ('levrier irlandais',1),
    ('levrier polonais',1),
    ('lhassa apso',1),
    ('malamute de l''alaska',1),
    ('manchester terrier',1),
    ('mastiff',1),
    ('mâtin de l''alentejo',1),
    ('mâtin des pyrenees',1),
    ('mâtin espagnol',1),
    ('mâtin napolitain',1),
    ('mudi',1),
    ('norfolk terrier',1),
    ('norwich terrier',1),
    ('petit basset griffon vendeen',1),
    ('petit bleu de gascogne',1),
    ('petit brabancon',1),
    ('petit chien courant suisse',1),
    ('petit chien hollandais de chasse au gibier d''eau',1),
    ('petit chien lion',1),
    ('petit chien russe',1),
    ('petit epagneul de munster',1),
    ('petit levrier italien',1),
    ('pinscher allemand',1),
    ('pinscher autrichien',1),
    ('pinscher nain',1),
    ('podenco d''ibiza',1),
    ('pointer anglais',1),
    ('poitevin',1),
    ('porcelaine',1),
    ('pudelpointer',1),
    ('puli',1),
    ('pumi',1),
    ('retriever a poil boucle',1),
    ('retriever a poil plat',1),
    ('retriever de la baie de chesapeake',1),
    ('retriever de la nouvelle ecosse',1),
    ('retriever du labrador',1),
    ('rottweiler',1),
    ('saint bernard',1),
    ('saluki',1),
    ('samoyede',1),
    ('schapendoes neerlandais',1),
    ('schipperke',1),
    ('schnauzer',1),
    ('schnauzer geant',1),
    ('schnauzer nain',1),
    ('sealyham terrier',1),
    ('setter anglais',1),
    ('setter gordon',1),
    ('setter irlandais rouge',1),
    ('setter irlandais rouge & blanc',1),
    ('shar pei',1),
    ('shiba',1),
    ('shih tzu',1),
    ('shikoku',1),
    ('skye terrier',1),
    ('sloughi',1),
    ('smous des pays bas',1),
    ('spinone',1),
    ('spitz',1),
    ('spitz de norrbotten',1),
    ('spitz des visigoths',1),
    ('spitz finlandais',1),
    ('spitz japonais',1),
    ('staffordshire bull terrier',1),
    ('staffordshire terrier americain',1),
    ('sussex spaniel',1),
    ('tchouvatch slovaque',1),
    ('teckel',1),
    ('terre neuve',1),
    ('terrier australien',1),
    ('terrier australien a poil soyeux',1),
    ('terrier bresilien',1),
    ('terrier d''agrement anglais noir et feu',1),
    ('terrier de boston',1),
    ('terrier de chasse allemand',1),
    ('terrier du reverend russell',1),
    ('terrier ecossais',1),
    ('terrier irlandais',1),
    ('terrier irlandais a poil doux',1),
    ('terrier irlandais glen of imaal',1),
    ('terrier jack russell',1),
    ('terrier japonais',1),
    ('terrier kerry blue',1),
    ('terrier noir russe',1),
    ('terrier tcheque',1),
    ('terrier tibetain',1),
    ('tosa',1),
    ('volpino italien',1),
    ('welsh corgi cardigan',1),
    ('welsh corgi pembroke',1),
    ('welsh springer spaniel',1),
    ('welsh terrier',1),
    ('west highland white terrier',1),
    ('whippet',1),
    ('yorkshire terrier',1);
