INSERT INTO `race` (`nom`,`id_espece`)VALUES
	 ('amadine cou-coupé',5),
    ('ara bleu et jaune',5),
    ('amazone',5),
    ('amazone à front bleu',5),
    ('astrild à joues orange',5),
    ('astrild cendré',5),
    ('bengali du Japon',5),
    ('cacatoès à huppe jaune',5),
    ('caille peinte',5),
    ('calopsitte élégante',5),
    ('canari',5),
    ('capucin bec-d''argent',5),
    ('capucin bec-de-plomb',5),
    ('capucin damier',5),
    ('capucin domino',5),
    ('cordonbleu à joues rouges',5),
    ('colombe diamant',5),
    ('diamant à gouttelettes',5),
    ('diamant à bavette',5),
    ('diamant à longue queue',5),
    ('diamant de Bichenov',5),
    ('diamant de Gould',5),
    ('diamant de Kittlitz',5),
    ('diamant mandarin',5),
    ('diamant modeste',5),
    ('diamant psittaculaire',5),
    ('diamant à queue rousse',5),
    ('géopélie diamant',5),
    ('gris du Gabon',5),
    ('grive musicienne',5),
    ('inséparable à face rose',5),
    ('inséparable rosegorge',5),
    ('liste des races et variétés de canaris',5),
    ('mainate religieux',5),
    ('merle noir',5),
    ('moineau domestique',5),
    ('moineau du Japon',5),
    ('padda de Java',5),
    ('paon bleu',5),
    ('passerin arc-en-ciel',5),
    ('passerin varié',5),
    ('perroquet',5),
    ('perroquet jaco',5),
    ('perruche',5),
    ('perruche à collier',5),
    ('perruche à croupion rouge',5),
    ('perruche catherine',5),
    ('perruche de Pennant',5),
    ('perruche Kakariki',5),
    ('perruche omnicolore',5),
    ('perruche ondulée',5),
    ('perruche ondulée',5),
    ('perruche Pennant',5),
    ('pione à bec rouge',5),
    ('pione à couronne blanche',5),
    ('pione à tête bleue',5),
    ('pione de Maximilien',5),
    ('pione noire',5),
    ('pione violette',5),
    ('scotch fancy',5),
    ('tourterelle domestique',5),
    ('youyou du Sénégal',5);