INSERT INTO `race` (`nom`,`id_espece`)VALUES
	('abronia graminea',6),
    ('agamura persica',6),
    ('basiliscus plumifrons',6),
    ('bradypodion pumilum',6),
    ('broadleysaurus major',6),
    ('caméléon casqué',6),
    ('furcifer pardalis',6),
    ('chondrodactylus bibronii',6),
    ('correlophus ciliatus',6),
    ('cyrtopodion scabrum',6),
    ('gecko diurne à queue bleue',6),
    ('gecko diurne orné de l''île maurice',6),
    ('gecko léopard',6),
    ('gekko badenii',6),
    ('hemidactylus frenatus',6),
    ('hemidactylus imbricatus',6),
    ('hemidactylus mabouia',6),
    ('hemitheconyx caudicinctus',6),
    ('heteronotia binoei',6),
    ('homopholis fasciata',6),
    ('iguana iguana',6),
    ('lampropeltis getula',6),
    ('lepidodactylus lugubris',6),
    ('naultinus grayii',6),
    ('oedura castelnaui',6),
    ('ouroborus cataphractus',6),
    ('paroedura androyensis',6),
    ('paroedura picta',6),
    ('phelsuma guimbeaui',6),
    ('phelsuma klemmeri',6),
    ('phelsuma lineata',6),
    ('phelsuma madagascariensis',6),
    ('phelsuma quadriocellata',6),
    ('phelsuma robertmertensi',6),
    ('phelsuma serraticauda',6),
    ('phelsuma standingi',6),
    ('phelsuma v-nigra',6),
    ('physignathus cocincinus',6),
    ('pogona barbata',6),
    ('pogona henrylawsoni',6),
    ('pogona vitticeps',6),
    ('ptychozoon kuhli',6),
    ('python de children',6);